name: build container - almalinux
run-name: Building container - AlmaLinux

on:
  workflow_dispatch:

jobs:
  build-arm64:
    name: build-container-almalinux-arm64
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04-arm

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run podman build - almalinux-arm
        run: |
          podman build -t ghcr.io/gbraad-dotfiles/almalinux:arm64 \
            --build-arg=BASE_IMAGE="ghcr.io/almalinux/9-init" \
            --build-arg=BASE_VERSION="9" \
            --build-arg=ARCH="aarch64" \
            -f .devcontainer/almalinux/Containerfile .

      - name: Run podman save - almalinux-arm
        run: |
          podman save ghcr.io/gbraad-dotfiles/almalinux:arm64 \
            --format=oci-dir -o oci-arm64

      - name: Run podman export - almalinux-arm
        run: |
          podman create --name almalinux-arm64 \
            ghcr.io/gbraad-dotfiles/almalinux:arm64          
          podman export almalinux-arm64 -o almalinux-arm64.tar
          gzip almalinux-arm64.tar

      - uses: actions/upload-artifact@v4
        with:
          name: oci-arm64
          path: oci-arm64/
          retention-days: 7

      - uses: actions/upload-artifact@v4
        with:
          name: rootfs-arm64
          path: almalinux-arm64.tar.gz
          retention-days: 7


  build-amd64:
    name: build-container-almalinux-amd64
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run podman build - almalinux
        run: |
          podman build -t ghcr.io/gbraad-dotfiles/almalinux:amd64 \
            --build-arg=BASE_IMAGE="ghcr.io/almalinux/9-init" \
            --build-arg=BASE_VERSION="9" \
            -f .devcontainer/almalinux/Containerfile .

      - name: Run podman save - almalinux
        run: |
          podman save ghcr.io/gbraad-dotfiles/almalinux:amd64 \
            --format=oci-dir -o oci-amd64

      - name: Run podman export - almalinux
        run: |
          podman create --name almalinux-amd64 \
            ghcr.io/gbraad-dotfiles/almalinux:amd64          
          podman export almalinux-amd64 -o almalinux-amd64.tar
          gzip almalinux-amd64.tar

      - uses: actions/upload-artifact@v4
        with:
          name: oci-amd64
          path: oci-amd64/
          retention-days: 7

      - uses: actions/upload-artifact@v4
        with:
          name: rootfs-amd64
          path: almalinux-amd64.tar.gz
          retention-days: 7


  push-manifest:
    name: build-container-almalinux
    needs: 
      - build-arm64
      - build-amd64
    runs-on: ubuntu-24.04

    steps:
      - name: Download arm64
        uses: actions/download-artifact@v4
        with:
          name: oci-arm64
          path: oci-arm64
      - uses: actions/download-artifact@v4
        with:
          name: rootfs-arm64
          path: rootfs
      - name: Download amd64
        uses: actions/download-artifact@v4
        with:
          name: oci-amd64
          path: oci-amd64
      - uses: actions/download-artifact@v4
        with:
          name: rootfs-amd64
          path: rootfs

      - name: Set release tag
        id: get-tag
        run: |
          echo "TAG=$(date +'%y%m%d')" >> $GITHUB_OUTPUT

      - name: Create manifest
        run: |
          podman manifest create almalinux-manifest

      - name: Add arm64 to manifest
        run: |
          podman manifest add almalinux-manifest oci:$(pwd)/oci-arm64
      - name: Add amd64 to manifest
        run: |
          podman manifest add almalinux-manifest oci:$(pwd)/oci-amd64

      - name: Login to registry
        run: |
          podman login ghcr.io -u ${{ github.actor }} \
            -p ${{ secrets.GITHUB_TOKEN }}

      - name: Push container to registry
        run: |
          podman manifest push almalinux-manifest docker://ghcr.io/gbraad-dotfiles/almalinux:latest
          podman manifest push almalinux-manifest docker://ghcr.io/gbraad-dotfiles/almalinux:9
          podman manifest push almalinux-manifest docker://ghcr.io/gbraad-dotfiles/almalinux:${{steps.get-tag.outputs.TAG}}

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get-tag.outputs.TAG }}
          files: rootfs/*.tar.gz
