name: Build and Push Fedora Container

on:
  workflow_dispatch:

jobs:
  build-arm64:
    name: build-container-fedora-arm64
    uses: ./.github/workflows/reusable-build-container.yml
    with:
      container_name: "fedora"
      arch: "arm64"
    secrets: inherit

  build-amd64:
    name: build-container-fedora-amd64
    uses: ./.github/workflows/reusable-build-container.yml
    with:
      container_name: "fedora"
      arch: "amd64"
    secrets: inherit

  push-manifest:
    name: build-container-fedora
    uses: ./.github/workflows/reusable-push-manifest.yml
    needs:
      - build-arm64
      - build-amd64
    with:
      container_name: "fedora"
    secrets: inherit
