name: Build and Push Ubuntu cloud diskimage

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:


jobs:
  build-diskimage-ubuntu-packer:
    uses: ./.github/workflows/reusable-build-diskimage-packer.yml
    with:
      container_name: ubuntu-cloud
