name: Build and Push Alpine Container

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: build-and-push-containers-alpine
    uses: ./.github/workflows/reusable-build-and-push-containers.yml
    with:
      container_name: "alpine"
    secrets: inherit
