name: build container - UBI9
run-name: Building container - UBI9

on:
  workflow_dispatch:

jobs:
  build:
    name: build-container-ubi9
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run podman build - ubi9
        run: |
          podman build -t ghcr.io/gbraad-dotfiles/ubi9:latest \
            --build-arg=BASE_IMAGE="registry.access.redhat.com/ubi9-init" \
            --build-arg=BASE_VERSION="9.5" \
            -f .devcontainer/ubi9/Containerfile .

      - name: Set release tag
        id: get-tag
        run: |
          echo "TAG=$(date +'%y%m%d')" >> $GITHUB_OUTPUT

      - name: Tag container
        run: |
          podman tag ghcr.io/gbraad-dotfiles/ubi9:latest \
            ghcr.io/gbraad-dotfiles/ubi9:9.5
          podman tag ghcr.io/gbraad-dotfiles/ubi9:latest \
            ghcr.io/gbraad-dotfiles/ubi9:${{steps.get-tag.outputs.TAG}}

      - name: Login to registry
        run: |
          podman login ghcr.io -u ${{ github.actor }} \
            -p ${{ secrets.GITHUB_TOKEN }}

      - name: Push container to registry
        run: |
          podman push ghcr.io/gbraad-dotfiles/ubi9:latest
          podman push ghcr.io/gbraad-dotfiles/ubi9:9.5
          podman push ghcr.io/gbraad-dotfiles/ubi9:${{steps.get-tag.outputs.TAG}}
