name: Build and Push AlmaLinux BootC Container

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push - AlmaLinux bootc
    uses: ./.github/workflows/reusable-build-and-push-bootable-containers.yml
    with:
      container_name: "almalinux"
    secrets: inherit
