name: build diskimages (bootc) - release
run-name: Building diskimages (bootc) - release
on:
  workflow_dispatch:

env:
    DISK_TYPE: qcow2
    ROOTFS: xfs
    ARCH: amd64
    BIB_IMAGE: quay.io/centos-bootc/bootc-image-builder:latest
    BODY: "Dotfiles disk images"

jobs:
  build:
    name: Build qcow2 diskimages
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04

    steps:
    - name: Remove unwanted stuff
      uses: gbraad-actions/remove-unwanted@v1

    - uses: actions/checkout@v4

    - name: Workaround podman issues in GH actions
      run: |
        # see https://github.com/osbuild/bootc-image-builder/issues/446
        sudo rm -rf /var/lib/containers/storage
        sudo mkdir -p /etc/containers
        echo -e "[storage]\ndriver = \"overlay\"\nrunroot = \"/run/containers/storage\"\ngraphroot = \"/var/lib/containers/storage\"" | sudo tee /etc/containers/storage.conf

    - name: Workarounds for GH runner diskspace
      run: |
        sudo mkdir -p /mnt/var/lib/containers
        sudo mount -o bind /mnt/var/lib/containers /var/lib/containers
        sudo mkdir /var/lib/containers/storage

    - name: Create shared user configuration
      run: touch config.toml

    - name: Build image - fedora
      id: build-image-fedora
      run: |
        mkdir -p ./output
        sudo podman pull ${{ env.IMAGE_NAME }}
        sudo podman run \
          --rm \
          -it \
          --privileged \
          --pull=newer \
          --security-opt label=type:unconfined_t \
          -v ./config.toml:/config.toml:ro \
          -v ./output:/output \
          -v /var/lib/containers/storage:/var/lib/containers/storage \
          ${{ env.BIB_IMAGE }} \
          --target-arch ${{ env.ARCH }} \
          --type ${{ env.DISK_TYPE }} \
          --rootfs ${{ env.ROOTFS }} \
          --local \
          ${{ env.IMAGE_NAME }}
      env:
        IMAGE_NAME: ghcr.io/gbraad-dotfiles/fedora-bootc:latest

    - name: Rename output file - dotfiles
      run: sudo mv ./output/qcow2/disk.qcow2 ./output/qcow2/fedora-disk.qcow2

    - name: Build image - centos
      id: build-image-centos
      run: |
        mkdir -p ./output
        sudo podman pull ${{ env.IMAGE_NAME }}
        sudo podman run \
          --rm \
          -it \
          --privileged \
          --pull=newer \
          --security-opt label=type:unconfined_t \
          -v ./config.toml:/config.toml:ro \
          -v ./output:/output \
          -v /var/lib/containers/storage:/var/lib/containers/storage \
          ${{ env.BIB_IMAGE }} \
          --target-arch ${{ env.ARCH }} \
          --type ${{ env.DISK_TYPE }} \
          --rootfs ${{ env.ROOTFS }} \
          --local \
          ${{ env.IMAGE_NAME }}
      env:
        IMAGE_NAME: ghcr.io/gbraad-dotfiles/centos-bootc:latest

    - name: Rename output file - dotfiles
      run: sudo mv ./output/qcow2/disk.qcow2 ./output/qcow2/centos-disk.qcow2

    - name: Set release tag
      run: echo "TAG=$(date +'%y%m%d')" >> $GITHUB_ENV

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.TAG }}
        name: Disk images (${{ env.TAG }})
        body: ${{ env.BODY }}
        artifacts: "output/bootiso/*.iso,./output/qcow2/*,"

