name: Build and Push Fedora Bootable Container

on:
  workflow_dispatch:

jobs:
  shared-config:
    name: Fetch Shared Configuration
    runs-on: ubuntu-latest
    outputs:
      container_name: "fedora"
      base_image: ${{ steps.config.outputs.base_image }}
      base_version: ${{ steps.config.outputs.base_version }}
      bootc_image: ${{ steps.config.outputs.bootc_image }}
      release_tag: ${{ steps.release.outputs.tag }}
    steps:
      - name: Fetch configuration and use output
        id: config
        uses: gbraad-actions/shared-config@v2
        with:
          config_repo: https://github.com/gbraad-dotfiles/shared-config.git
          config_file: containers/fedora.ini
          use_output: true
      - name: Set release tag
        id: release
        run: |
          echo "tag=$(date +'%y%m%d')" >> $GITHUB_OUTPUT

  build-amd64:
    needs: shared-config
    name: build-container-fedora-bootc
    uses: ./.github/workflows/reusable-build-container-bootc.yml
    with:
      container_name: ${{ needs.shared-config.outputs.container_name }}
      bootc_image: ${{ needs.shared-config.outputs.bootc_image }}      
      base_version: ${{ needs.shared-config.outputs.base_version }}
      release_tag: ${{ needs.shared-config.outputs.release_tag }}
      arch: "amd64"
    secrets: inherit
