name: build process
run-name: Build process

on:
  workflow_dispatch:


jobs:

  trigger-build-container-almalinux:
    runs-on: ubuntu-latest
    steps:
      - name: Start AlmaLinux container build
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-container-almalinux.yml',
              ref: context.ref,
            });


  trigger-build-container-centos:
    runs-on: ubuntu-latest
    steps:
      - name: Start CentOS container build
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-container-centos.yml',
              ref: context.ref,
            });


  trigger-build-container-debian:
    runs-on: ubuntu-latest
    steps:
      - name: Start Debian container build
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-container-debian.yml',
              ref: context.ref,
            });  

          
  trigger-build-container-fedora:
    runs-on: ubuntu-latest
    steps:
      - name: Start Fedora container build
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-container-fedora.yml',
              ref: context.ref,
            });      


  trigger-build-container-ubi9:
    runs-on: ubuntu-latest
    steps:
      - name: Start UBI9 container build
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-container-ubi9.yml',
              ref: context.ref,
            });     


  trigger-build-container-alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Start Alpine container build
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-container-alpine.yml',
              ref: context.ref,
            });     


  trigger-build-container-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Start Ubuntu container build
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-container-ubuntu.yml',
              ref: context.ref,
            });   
