name: build container - debian
run-name: Building container - Debian

on:
  workflow_dispatch:

jobs:
  build:
    name: build-container-debian
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run podman build - debian
        run: |
          podman build -t ghcr.io/gbraad-dotfiles/debian:latest \
            -f .devcontainer/debian/Containerfile .

      - name: Set release tag
        id: get-tag
        run: |
          echo "TAG=$(date +'%y%m%d')" >> $GITHUB_OUTPUT

      - name: Tag container
        run: |
          podman tag ghcr.io/gbraad-dotfiles/debian:latest \
            ghcr.io/gbraad-dotfiles/debian:bookworm
          podman tag ghcr.io/gbraad-dotfiles/debian:latest \
            ghcr.io/gbraad-dotfiles/debian:${{steps.get-tag.outputs.TAG}}

      - name: Login to registry
        run: |
          podman login ghcr.io -u ${{ github.actor }} \
            -p ${{ secrets.GITHUB_TOKEN }}

      - name: Push container to registry
        run: |
          podman push ghcr.io/gbraad-dotfiles/debian:latest
          podman push ghcr.io/gbraad-dotfiles/debian:bookworm
          podman push ghcr.io/gbraad-dotfiles/debian:${{steps.get-tag.outputs.TAG}}
