name: Build and Push CentOS container

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request: {}


jobs:
  build-and-push:
    name: Build and push - CentOS
    uses: ./.github/workflows/reusable-build-and-push-containers.yml
    with:
      container_name: "centos"
    secrets: inherit
