name: Build and Push UBI9 Container

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: build-and-push-containers-ubi9
    uses: ./.github/workflows/reusable-build-and-push-containers.yml
    with:
      container_name: "ubi9"
    secrets: inherit
