name: Build and Push Fedora BootC Container

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push - Fedora bootc
    uses: ./.github/workflows/reusable-build-and-push-bootable-containers.yml
    with:
      container_name: "fedora"
    secrets: inherit
