name: Build and Push AlmaLinux Container

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: build-and-push-containers-almalinux
    uses: ./.github/workflows/reusable-build-and-push-containers.yml
    with:
      container_name: "almalinux"
    secrets: inherit
