name: Build and Push Debian Container

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: build-and-push-containers-debian
    uses: ./.github/workflows/reusable-build-and-push-containers.yml
    with:
      container_name: "debian"
    secrets: inherit
