name: Build and Push Fedora Container

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request: {}


jobs:
  build-and-push:
    name: Build and push - Fedora
    uses: ./.github/workflows/reusable-build-and-push-containers.yml
    with:
      container_name: "fedora"
    secrets: inherit
