name: Build and Push UBI9 container

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request: {}


jobs:
  build-and-push:
    name: Build and push - UBI9
    uses: ./.github/workflows/reusable-build-and-push-containers.yml
    with:
      container_name: "ubi9"
    secrets: inherit
