name: build container - Alpine
run-name: Building container - Alpine

on:
  workflow_dispatch:

jobs:
  build-arm64:
    name: build-container-alpine-arm64
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04-arm

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run podman build - alpine-arm
        run: |
          podman build -t ghcr.io/gbraad-dotfiles/alpine:arm64 \
            --build-arg=BASE_IMAGE="alpine" \
            --build-arg=BASE_VERSION="3.21" \
            --build-arg=ARCH="aarch64" \
            -f .devcontainer/alpine/Containerfile .

      - name: Run podman save - alpine-arm
        run: |
          podman save ghcr.io/gbraad-dotfiles/alpine:arm64 \
            --format=oci-dir -o oci-arm64

      - name: Run podman export - alpine-arm
        run: |
          podman create --name alpine-arm64 \
            ghcr.io/gbraad-dotfiles/alpine:arm64          
          podman export alpine-arm64 -o alpine-arm64.tar
          gzip alpine-arm64.tar

      - uses: actions/upload-artifact@v4
        with:
          name: oci-arm64
          path: oci-arm64/
          retention-days: 7

      - uses: actions/upload-artifact@v4
        with:
          name: rootfs-arm64
          path: alpine-arm64.tar.gz
          retention-days: 7

  build-amd64:
    name: build-container-alpine-amd64
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run podman build - alpine
        run: |
          podman build -t ghcr.io/gbraad-dotfiles/alpine:amd64 \
            --build-arg=BASE_IMAGE="alpine" \
            --build-arg=BASE_VERSION="3.21" \
            -f .devcontainer/alpine/Containerfile .

      - name: Run podman save - alpine
        run: |
          podman save ghcr.io/gbraad-dotfiles/alpine:amd64 \
            --format=oci-dir -o oci-amd64

      - name: Run podman export - alpine
        run: |
          podman create --name alpine-amd64 \
            ghcr.io/gbraad-dotfiles/alpine:amd64          
          podman export alpine-amd64 -o alpine-amd64.tar
          gzip alpine-amd64.tar

      - uses: actions/upload-artifact@v4
        with:
          name: oci-amd64
          path: oci-amd64/
          retention-days: 7

      - uses: actions/upload-artifact@v4
        with:
          name: rootfs-amd64
          path: alpine-amd64.tar.gz
          retention-days: 7


  push-manifest:
    name: build-container-alpine
    needs: 
      - build-arm64
      - build-amd64
    runs-on: ubuntu-24.04

    steps:
      - name: Download arm64
        uses: actions/download-artifact@v4
        with:
          name: oci-arm64
          path: oci-arm64
      - uses: actions/download-artifact@v4
        with:
          name: rootfs-arm64
          path: rootfs
      - name: Download amd64
        uses: actions/download-artifact@v4
        with:
          name: oci-amd64
          path: oci-amd64
      - uses: actions/download-artifact@v4
        with:
          name: rootfs-amd64
          path: rootfs

      - name: Set release tag
        id: get-tag
        run: |
          echo "TAG=$(date +'%y%m%d')" >> $GITHUB_OUTPUT

      - name: Create manifest
        run: |
          podman manifest create ubi-manifest

      - name: Add arm64 to manifest
        run: |
          podman manifest add ubi-manifest oci:$(pwd)/oci-arm64
      - name: Add amd64 to manifest
        run: |
          podman manifest add ubi-manifest oci:$(pwd)/oci-amd64

      - name: Login to registry
        run: |
          podman login ghcr.io -u ${{ github.actor }} \
            -p ${{ secrets.GITHUB_TOKEN }}

      - name: Push container to registry
        run: |
          podman manifest push ubi-manifest docker://ghcr.io/gbraad-dotfiles/alpine:latest
          podman manifest push ubi-manifest docker://ghcr.io/gbraad-dotfiles/alpine:3.21
          podman manifest push ubi-manifest docker://ghcr.io/gbraad-dotfiles/alpine:${{steps.get-tag.outputs.TAG}}

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get-tag.outputs.TAG }}
          files: rootfs/*.tar.gz
