name: build containers
run-name: building containers
on:
  push:
    branches:
      - "main"
  pull_request: {}
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run podman build - fedora
        run: podman build -t ghcr.io/gbraad/dotfiles/fedora:latest -f .devcontainer/fedora/Containerfile .
      - name: Push image to ghcr.io - fedora
        run: podman push --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} ghcr.io/gbraad/dotfiles/fedora:latest
      - name: Run podman build - debian
        run: podman build -t ghcr.io/gbraad/dotfiles/debian:latest -f .devcontainer/debian/Containerfile .
      - name: Push image to ghcr.io - debian
        run: podman push --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} ghcr.io/gbraad/dotfiles/debian:latest