name: Build and Push AlmaLinux Container

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request: {}


jobs:
  build-and-push:
    name: Build and push - AlmaLinux
    uses: ./.github/workflows/reusable-build-and-push-containers.yml
    with:
      container_name: "almalinux"
    secrets: inherit
