name: Build and Push Fedora cloud diskimage

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:


jobs:
  build-diskimage-fedora-machine:
    uses: ./.github/workflows/reusable-build-diskimage-machine.yml
    with:
      container_name: fedora-cloud
    secrets: inherit
