name: Build and Push UBI9 Container

on:
  workflow_dispatch:

jobs:
  build-arm64:
    name: build-container-ubi-arm64
    uses: ./.github/workflows/reusable-build-container.yml
    with:
      container_name: "ubi9"
      arch: "arm64"
    secrets: inherit

  build-amd64:
    name: build-container-ubi9-amd64
    uses: ./.github/workflows/reusable-build-container.yml
    with:
      container_name: "ubi9"
      arch: "amd64"
    secrets: inherit

  push-manifest:
    name: build-container-ubi9
    uses: ./.github/workflows/reusable-push-manifest.yml
    needs:
      - build-arm64
      - build-amd64
    with:
      container_name: "ubi9"
    secrets: inherit
