name: build bootc containers and diskimage
run-name: Building bootc containers and diskimages

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:


jobs:
  build-diskimage-fedora-packer:
    uses: ./.github/workflows/reusable-build-diskimage-packer.yml
    with:
      target: fedora

  build-diskimage-debian-packer:
    uses: ./.github/workflows/reusable-build-diskimage-packer.yml
    with:
      target: debian

  build-diskimage-ubuntu-packer:
    uses: ./.github/workflows/reusable-build-diskimage-packer.yml
    with:
      target: ubuntu


  build-container-almalinux-bootc:
    uses: ./.github/workflows/build-container-almalinux-bootc.yml

  build-container-centos-bootc:
    uses: ./.github/workflows/build-container-centos-bootc.yml
            
  build-container-fedora-bootc:
    uses: ./.github/workflows/build-container-fedora-bootc.yml


  build-diskimage-almalinux-bootc:
    needs: build-container-almalinux-bootc
    uses: ./.github/workflows/build-diskimage-almalinux-bootc.yml

  build-diskimage-centos:
    needs: build-container-centos-bootc
    uses: ./.github/workflows/build-diskimage-centos-bootc.yml

  build-diskimage-fedora:
    needs: build-container-fedora-bootc
    uses: ./.github/workflows/build-diskimage-fedora-bootc.yml
