name: build container - almalinux
run-name: Building container - AlmaLinux

on:
  workflow_dispatch:

jobs:
  build:
    name: build-container-almalinux
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run podman build - almalinux
        run: |
          podman build -t ghcr.io/gbraad-dotfiles/almalinux:latest \
            --build-arg=BASE_IMAGE="ghcr.io/almalinux/9-init" \
            --build-arg=BASE_VERSION="9" \
            -f .devcontainer/almalinux/Containerfile .

      - name: Tag and push image to ghcr.io - almalinux
        run: |
          DATE=$(date +"%y%m%d")
          podman tag ghcr.io/gbraad-dotfiles/almalinux:latest \
            ghcr.io/gbraad-dotfiles/almalinux:9
          podman tag ghcr.io/gbraad-dotfiles/almalinux:latest \
            ghcr.io/gbraad-dotfiles/almalinux:${DATE}
          podman login ghcr.io -u ${{ github.actor }} \
            -p ${{ secrets.GITHUB_TOKEN }}
          podman push ghcr.io/gbraad-dotfiles/almalinux:${DATE}
          podman push ghcr.io/gbraad-dotfiles/almalinux:9
          podman push ghcr.io/gbraad-dotfiles/almalinux:latest

