name: build container - fedora-bootc
run-name: Building container - Fedora (bootc)
on:
  workflow_dispatch:

jobs:
  build:
    name: build-container-fedora-bootc    
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run podman build - fedora-bootc
        run: |
          podman build -t ghcr.io/gbraad-dotfiles/fedora-bootc:latest \
            --build-arg=BASE_IMAGE="quay.io/fedora/fedora-bootc" \
            --build-arg=BASE_VERSION=41 \
            --build-arg=HOMEBASE="/var/home" \
            --build-arg=USER_PASSWD="password" \
            --build-arg=ROOTHOME="/var/roothome" \
            -f .devcontainer/fedora/Containerfile .
      - name: Tag and push image to ghcr.io - fedora-bootc
        run: |
          DATE=$(date +"%y%m%d")
          podman tag ghcr.io/gbraad-dotfiles/fedora-bootc:latest \
            ghcr.io/gbraad-dotfiles/fedora-bootc:41
          podman tag ghcr.io/gbraad-dotfiles/fedora-bootc:latest \
            ghcr.io/gbraad-dotfiles/fedora-bootc:${DATE}
          podman login ghcr.io -u ${{ github.actor }} \
            -p ${{ secrets.GITHUB_TOKEN }}
          podman push ghcr.io/gbraad-dotfiles/fedora-bootc:${DATE}
          podman push ghcr.io/gbraad-dotfiles/fedora-bootc:41
          podman push ghcr.io/gbraad-dotfiles/fedora-bootc:latest
