name: Build and Push CentOS bootc diskimage

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:


jobs:
  build-container-centos-bootc:
    name: Build and push - CentOS bootc
    uses: ./.github/workflows/reusable-build-and-push-bootable-containers.yml
    with:
      container_name: "centos"
    secrets: inherit

  build-diskimage-centos:
    needs: build-container-centos-bootc
    uses: ./.github/workflows/reusable-build-diskimage-bootc.yml
    with:
      container_name: "centos"
    secrets: inherit
