name: Build and Push Fedora Bootable Container

on:
  workflow_dispatch:

jobs:
  build-amd64:
    name: build-container-fedora-bootc
    uses: ./.github/workflows/reusable-build-container-bootc.yml
    with:
      container_name: "fedora"
      arch: "amd64"
    secrets: inherit
