name: Build and Push Fedora Container

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push - Fedora
    uses: ./.github/workflows/reusable-build-and-push-containers.yml
    with:
      container_name: "fedora"
    secrets: inherit
