name: Build and Push CentOS Container

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push - CentOS
    uses: ./.github/workflows/reusable-build-and-push-containers.yml
    with:
      container_name: "centos"
    secrets: inherit
