name: mark latest as stable - fedora-bootc
run-name: Mark latest as stable - fedora-bootc

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "0 0 * * 0"

jobs:
  mark-as-stable:
    name: mark-as-stable
    uses: ./.github/workflows/reusable-mark-as-stable.yml
    with:
      container_name: "fedora-bootc"
    secrets: inherit
