name: mark latest as stable
run-name: Mark latest as stable

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "0 0 * * 0"

jobs:
  mark-as-stable-fedora:
    name: mark-as-stable-fedora
    uses: ./.github/workflows/reusable-mark-as-stable.yml
    with:
      container_name: "fedora"
    secrets: inherit

  mark-as-stable-fedora-bootc:
    name: mark-as-stable-fedora-bootc
    uses: ./.github/workflows/reusable-mark-as-stable.yml
    with:
      container_name: "fedora-bootc"
    secrets: inherit

  mark-as-stable-centos:
    name: mark-as-stable-centos
    uses: ./.github/workflows/reusable-mark-as-stable.yml
    with:
      container_name: "centos"
    secrets: inherit

  mark-as-stable-centos-bootc:
    name: mark-as-stable-centos-bootc
    uses: ./.github/workflows/reusable-mark-as-stable.yml
    with:
      container_name: "centos-bootc"
    secrets: inherit

  mark-as-stable-almalinux:
    name: mark-as-stable-almalinux
    uses: ./.github/workflows/reusable-mark-as-stable.yml
    with:
      container_name: "almalinux"
    secrets: inherit

  mark-as-stable-almalinux-bootc:
    name: mark-as-stable-almalinux-bootc
    uses: ./.github/workflows/reusable-mark-as-stable.yml
    with:
      container_name: "almalinux-bootc"
    secrets: inherit

  mark-as-stable-ubi9:
    name: mark-as-stable-ubi9
    uses: ./.github/workflows/reusable-mark-as-stable.yml
    with:
      container_name: "ubi9"
    secrets: inherit

  mark-as-stable-debian:
    name: mark-as-stable-debian
    uses: ./.github/workflows/reusable-mark-as-stable.yml
    with:
      container_name: "debian"
    secrets: inherit

  mark-as-stable-ubuntu:
    name: mark-as-stable-ubuntu
    uses: ./.github/workflows/reusable-mark-as-stable.yml
    with:
      container_name: "ubuntu"
    secrets: inherit

  mark-as-stable-alpine:
    name: mark-as-stable-alpine
    uses: ./.github/workflows/reusable-mark-as-stable.yml
    with:
      container_name: "alpine"
    secrets: inherit


  trigger-sync-repos:
    runs-on: ubuntu-latest
    needs:
      - mark-as-stable-fedora
      - mark-as-stable-fedora-bootc
      - mark-as-stable-centos
      - mark-as-stable-centos-bootc
      - mark-as-stable-almalinux
      - mark-as-stable-almalinux-bootc
      - mark-as-stable-ubi9
      - mark-as-stable-debian
      - mark-as-stable-ubuntu
      - mark-as-stable-alpine
    steps:
      - name: Trigger sync-repo-gbraad.yml
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'sync-repo-gbraad.yml',
              ref: context.ref,
            });
      - name: Trigger sync-repo-devenv.yml
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'sync-repo-devenv.yml',
              ref: context.ref,
            });
      - name: Trigger sync-repo-redhat.yml
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'sync-repo-redhat.yml',
              ref: context.ref,
            });
