name: Test bootc images using macadam/machine

on:
  workflow_call:
    inputs:
      prefix_name:
        description: "Name of the image to run with machine and macadam (e.g., dotfedora)"
        required: false
        type: string
        default: "dotfedora"
      image_username:
        description: "Username for log in to the image"
        required: false
        type: string
        default: "gbraad"
      runs-on:
        description: "Target runner"
        required: true
        type: string
        default: "ubuntu-latest"
      arch:
        description: "Target architecture (e.g., arm64, amd64)"
        required: false
        type: string
        default: "amd64"

jobs:
  test-macadam:
    runs-on: ${{ inputs.runs-on }}${{ inputs.arch == 'arm64' && '-arm' || '' }}

    steps:
      - name: Enable linger and create user session (workaround)
        uses: gbraad-actions/blacksmith-user-session@main

      - name: Allow unprivileged userns (workaround)
        uses: gbraad-actions/warpbuild-unprivileged-userns@main

      - name: Get last 3 chars of hostname
        id: runner_id
        run: |
          echo "last3=${HOSTNAME: -3}" >> $GITHUB_OUTPUT

      - name: Remove unwanted stuff
        uses: gbraad-devenv/remove-unwanted@v1

      - name: Tailscale setup (host)
        uses: gbraad-actions/tailscale-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          args: --ssh --accept-dns=false --operator=runner --advertise-exit-node
          hostname: "machine-${{ inputs.arch }}-${{ steps.runner_id.outputs.last3 }}"

      - name: Create and share userdirs
        run: |
          cd ${{ github.workspace }}
          mkdir -p Projects Documents Downloads
          ln -s ${{ github.workspace }}/Projects  ${HOME}/Projects
          ln -s ${{ github.workspace }}/Documents ${HOME}/Documents
          ln -s ${{ github.workspace }}/Downloads ${HOME}/Downloads
          tailscale drive share projects ${HOME}/Projects
          tailscale drive share documents ${HOME}/Documents
          tailscale drive share downloads ${HOME}/Downloads
          
      - name: Dotfiles (install from action)
        uses: gbraad-dotfiles/install-action@main
        with:
          upstream: true

      - name: Install required virtualization software
        continue-on-error: true
        uses: gbraad-actions/setup-virtualization@main

      - name: Install containers tools (optional)
        continue-on-error: true
        uses: gbraad-actions/setup-container-tools@v1

      - name: Compile macadam
        uses: gbraad-actions/zsh-action@main
        with:
          as_user: runner
          run: |
            # prepare
            apps projects/gvproxy source checkout
            apps projects/macadam source checkout
            devenv gofedora noinit

            # gvproxy
            apps projects/gvproxy make
            apps projects/gvproxy cp
            
            # macadam
            apps projects/macadam make
            apps projects/macadam cp
          
      - name: Write machine key to file
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.SSH_MACHINE_PRIVATE }}" > ~/.ssh/id_machine
          chmod 600 ~/.ssh/id_machine
          printf "%s\n" "${{ secrets.SSH_MACHINE_PUBLIC }}"  > ~/.ssh/id_machine.pub
          
      - name: Prepare images for use with macadam
        uses: gbraad-actions/zsh-action@main
        with:
          as_user: runner
          run: |
            # prepare
            mkdir -p ~/DiskImages
            machine ${{ inputs.prefix_name }} download
      
      - name: Init image with macadam
        uses: gbraad-actions/macadam-action@main
        with:
          disk_image: ~/DiskImages/${{ inputs.prefix_name }}.qcow2
          image_username: ${{ inputs.image_username }}
          identity_path: ~/.ssh/id_machine

      - name: Start VM with macadam
        uses: gbraad-actions/zsh-action@main
        with:
          as_user: runner
          run: |
            macadam list
            macadam start

      - name: Run test command with macadam
        uses: gbraad-actions/zsh-action@main
        with:
          as_user: runner
          run: |
            macadam ssh cat /etc/os-release

      - name: Bootc switch VM to golang image
        uses: gbraad-actions/zsh-action@main
        with:
          as_user: runner
          run: |
            macadam ssh sudo bootc status
            macadam ssh dotfiles machine golang switch
            # macadam ssh does not source the profile

      - name: Restart VM using macadam
        uses: gbraad-actions/zsh-action@main
        with:
          as_user: runner
          run: |
            macadam stop
            macadam start

      - name: Run golang with macadam
        uses: gbraad-actions/zsh-action@main
        with:
          as_user: runner
          run: |
            macadam ssh sudo bootc status
            macadam ssh go version

      - name: Hang around
        if: ${{ failure() }}
        run: |
          sleep 18000
