name: reusable-build-container

on:
  workflow_call:
    inputs:
      container_name:
        description: "Name of the container (e.g., fedora, ubi9)"
        required: true
        type: string
      arch:
        description: "Architecture for the container (e.g., arm64, amd64)"
        required: true
        type: string

jobs:
  build:
    name: Build Container
    runs-on: ${{ inputs.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Fetch shared configuration
        uses: gbraad-actions/shared-config@v1
        with:
          config_repo: https://github.com/gbraad-dotfiles/shared-config.git
          config_file: containers/${{ inputs.container_name }}.ini

      - name: Build container
        run: |
          podman build -t ghcr.io/${{ github.repository }}/${{ inputs.container_name }}-bootc:latest \
            --build-arg=BASE_IMAGE="${{ env.BOOTC_IMAGE }}" \
            --build-arg=BASE_VERSION="${{ env.BASE_VERSION }}" \
            --build-arg=ARCH="${{ inputs.arch }}" \
            --build-arg=HOMEBASE="/var/home" \
            --build-arg=USER_PASSWD="password" \
            --build-arg=ROOTHOME="/var/roothome" \
            -f .devcontainer/${{ inputs.container_name }}/Containerfile

      - name: Set release tag
        id: get-tag
        run: |
          echo "TAG=$(date +'%y%m%d')" >> $GITHUB_OUTPUT

      - name: Tag container
        run: |
          podman tag ghcr.io/${{ github.repository }}/${{ inputs.container_name }}-bootc:latest \
            ghcr.io/${{ github.repository }}/${{ inputs.container_name }}-bootc:${{ env.BASE_VERSION }}
          podman tag ghcr.io/${{ github.repository }}/${{ inputs.container_name }}-bootc:latest \
            ghcr.io/${{ github.repository }}/${{ inputs.container_name }}-bootc:${{ steps.get-tag.outputs.TAG }}

      - name: Login to registry
        run: |
          podman login ghcr.io -u ${{ github.actor }} \
            -p ${{ secrets.GITHUB_TOKEN }}

      - name: Push container to registry
        run: |
          podman push ghcr.io/${{ github.repository }}/${{ inputs.container_name }}-bootc:latest
          podman push ghcr.io/${{ github.repository }}/${{ inputs.container_name }}-bootc:${{ env.BASE_VERSION }}
          podman push ghcr.io/${{ github.repository }}/${{ inputs.container_name }}-bootc:${{ steps.get-tag.outputs.TAG }}
