name: Sync to downstream repo - gbraad-redhat

on:
    workflow_call:
      inputs:
        repo:
          description: "Target repository to sync to"
          required: true
          type: string

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Push to destination repository
        run: |
          git config --unset-all http.https://github.com/.extraheader
          git remote add downstream https://gbraad:${{ secrets.PAT }}@${{ inputs.repo }}.git
          git push -f downstream main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
