name: reusable-tailscale-ssh-container

on:
  workflow_call:
    inputs:
      container_name:
        description: "Name of the container (e.g., fedora, ubi9)"
        required: true
        type: string
      base_version:
        description: "Base version identifier"
        required: false
        type: string
        default: "latest"
      runs-on:
        description: "Target runner"
        required: true
        type: string
        default: "ubuntu-latest"
      arch:
        description: "Architecture for the container (e.g., arm64, amd64)"
        required: true
        type: string
        default: "amd64"
      sudo-change-shell:
        description: "Whether to use sudo for chsh"
        required: false
        type: boolean
        default: false

defaults:
  run:
    shell: bash

jobs:
  dotfiles-test:
    runs-on: ${{ inputs.runs-on }}${{ inputs.arch == 'arm64' && '-arm' || '' }}
    
    steps:

      - name: Enable linger and create user session (workaround)
        if: ${{ startsWith(runner.name, 'blacksmith-') }}
        run: |
          sudo loginctl enable-linger runner
          sudo apt-get install -y systemd-container
          sudo machinectl shell runner@ /usr/bin/echo "User session created"

      - name: Workaround - fixes compaudit
        run: |
          sudo chmod go-w /usr/share/zsh/vendor-completions
          sudo chmod go-w /usr/share/zsh

      - name: Get last 3 chars of hostname
        id: runner_id
        run: |
          echo "last3=${HOSTNAME: -3}" >> $GITHUB_OUTPUT

      - name: Remove unwanted stuff
        uses: gbraad-devenv/remove-unwanted@v1

      - name: Tailscale
        uses: gbraad-actions/tailscale-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          args: --ssh --accept-dns=false --operator=runner --advertise-exit-node
          hostname: "dotfiles-${{ inputs.arch }}-${{ steps.runner_id.outputs.last3 }}"

      - name: Create and share userdirs
        run: |
          cd ${{ github.workspace }}
          mkdir -p Projects Documents Downloads
          ln -s ${{ github.workspace }}/Projects  ${HOME}/Projects
          ln -s ${{ github.workspace }}/Documents ${HOME}/Documents
          ln -s ${{ github.workspace }}/Downloads ${HOME}/Downloads
          tailscale drive share projects ${HOME}/Projects
          tailscale drive share documents ${HOME}/Documents
          tailscale drive share downloads ${HOME}/Downloads

      - name: Dotfiles (install from action)
        uses: gbraad-dotfiles/install-action@main
        with:
          sudo-change-shell: ${{ inputs.sudo-change-shell }}

      - name: Run system container with `podman`
        run: |
          IMAGE_USER="gbraad"
          podman run -d --name dotfiles \
            --hostname dot${{ inputs.container_name }}-${{ inputs.arch }}-${{ steps.runner_id.outputs.last3 }} \
            --systemd=always --cap-add=NET_RAW --cap-add=NET_ADMIN \
            --cap-add=SYS_ADMIN --device=/dev/net/tun --device=/dev/fuse \
            -v ${HOME}/Projects:/home/${IMAGE_USER}/Projects \
            -v ${HOME}/Documents:/home/${IMAGE_USER}/Documents \
            -v ${HOME}/Downloads:/home/${IMAGE_USER}/Downloads \
            ghcr.io/gbraad-dotfiles/${{ inputs.container_name }}:${{ inputs.base_version }}
          podman exec dotfiles chown ${IMAGE_USER} /home/${IMAGE_USER}/Projects
          podman exec dotfiles chown ${IMAGE_USER} /home/${IMAGE_USER}/Documents
          podman exec dotfiles chown ${IMAGE_USER} /home/${IMAGE_USER}/Downloads

      - name: Tailscale setup (root)
        run: |
          sleep 1
          until podman exec dotfiles tailscale up \
            --auth-key ${TAILSCALE_AUTHKEY} \
            --ssh --accept-dns=false \
            --operator=gbraad \
            --advertise-exit-node
          do
              sleep 0.1
          done
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY}}

      - name: Hang around
        run: |
          until podman exec dotfiles systemctl is-active --quiet tailscaled
          do
               sleep 1
          done
          IP=`podman exec dotfiles tailscale ip -4`
          echo "Use the following command to connect \`tailscale ssh gbraad@${IP}\`"
          IP=`tailscale ip -4`
          echo "Use the following command to debug from the host \`tailscale ssh runner@${IP}\`"
          sleep 18000

      - name: Message user; 1 hour
        run: |
          sudo wall "about 1 hour remaining"
          sleep 1800

      - name: Message user; 20 minutes
        run: |
          sudo wall "20 minutes remaining"
          sleep 1200

      - name: Upload Artifact - Projects
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: projects
          path: ${{ github.workspace }}/Projects/
          retention-days: 1
          include-hidden-files: true
  
      - name: Upload Artifact - Documents
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: documents
          path: ${{ github.workspace }}/Documents/
          retention-days: 1
          include-hidden-files: true

      - name: Upload Artifact - Downloads
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: downloads
          path: ${{ github.workspace }}/Downloads/
          retention-days: 1
          include-hidden-files: true

      - name: Hang around
        run: |
          sleep infinity
