name: Sync to downstream repo - gbraad

on:
  workflow_dispatch:

jobs:
  sync:
    name: Sync to gbraad/dotfiles-stable
    uses: ./.github/workflows/reusable-sync-repo.yml
    with:
      repo: "github.com/gbraad/dotfiles-stable"
    secrets: inherit
