name: Sync to downstream repo - gbraad-devenv

on:
  workflow_dispatch:

jobs:
  sync:
    name: Sync to gbraad-devenv/dotfiles
    uses: ./.github/workflows/reusable-sync-repo.yml
    with:
      repo: "github.com/gbraad-devenv/dotfiles"
    secrets: inherit
