name: tailscale-ssh-debian-amd64

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH - Debian AMD64
    uses: ./.github/workflows/reusable-tailscale-ssh.yml
    with:
      container_name: "debian"
      base_version: "latest"
      runs-on: "ubuntu-latest"
      arch: "amd64"
    secrets: inherit
