name: tailscale-ssh-ubi9-arm64

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH - UBI9 ARM64
    uses: ./.github/workflows/reusable-tailscale-ssh.yml
    with:
      container_name: "ubi9"
      base_version: "latest"
      arch: "arm64"
    secrets: inherit
