name: tailscale-ssh-ubi9-amd64-blacksmith

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH - UBI9 AMD64
    uses: ./.github/workflows/reusable-tailscale-ssh-devenv.yml
    with:
      prefix_name: "dotubi9"
      runs-on: "blacksmith-2vcpu-ubuntu-2404"
      arch: "amd64"
      sudo-change-shell: true
    secrets: inherit
