name: tailscale-ssh-machine-ubuntu

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH Machine - Ubuntu
    uses: ./.github/workflows/reusable-tailscale-ssh-machine.yml
    with:
      prefix_name: "dotubuntu"
      runs-on: "ubuntu-latest"
    secrets: inherit
