name: tailscale-ssh-almalinux-amd64-blacksmith

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH - AlmaLinux AMD64
    uses: ./.github/workflows/reusable-tailscale-ssh-container.yml
    with:
      container_name: "almalinux"
      base_version: "latest"
      runs-on: "blacksmith-2vcpu-ubuntu-2404"
      arch: "amd64"
      sudo-change-shell: true
    secrets: inherit
