name: tailscale-ssh-ubi9-amd64

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH - UBI9 AMD64
    uses: ./.github/workflows/reusable-tailscale-ssh.yml
    with:
      container_name: "ubi9"
      base_version: "latest"
      arch: "amd64"
    secrets: inherit
