name: tailscale-ssh-dotscreen-amd64
run-name: Tailscale SSH for dotscreen command

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH dotscreen - Ubuntu
    uses: ./.github/workflows/reusable-tailscale-ssh-dotscreen.yml
    with:
      runs-on: "ubuntu-24.04"
      hostname: "dotscreen"
    secrets: inherit
