name: tailscale-ssh-arm
run-name: Tailscale SSH with install action on Arm

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    runs-on: ubuntu-24.04-arm
    
    steps:
      - name: Remove unwanted stuff
        uses: gbraad-devenv/remove-unwanted@v1

      - name: Tailscale
        uses: gbraad-actions/tailscale-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          args: --ssh --accept-dns=false --operator=runner
          hostname: dotfiles-arm

      - name: Dotfiles
        uses: gbraad-dotfiles/install-dotfiles-action@v1

      - name: Install podman (optional)
        continue-on-error: true
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Hang around
        run: |
          IP=`tailscale ip -4`
          echo "Use the following command to connect \`tailscale ssh runner@${IP}\`"
          sleep infinity
