name: tailscale-ssh-almalinux-amd64

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH - AlmaLinux AMD64
    uses: ./.github/workflows/reusable-tailscale-ssh-devenv.yml
    with:
      prefix_name: "dotalmalinux"
      runs-on: "ubuntu-latest"
      arch: "amd64"
    secrets: inherit
