name: tailscale-ssh-almalinux-arm64-blacksmith

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH - AlmaLinux ARM64
    uses: ./.github/workflows/reusable-tailscale-ssh-devenv.yml
    with:
      prefix_name: "dotalmalinux"
      runs-on: "blacksmith-2vcpu-ubuntu-2404"
      arch: "arm64"
    secrets: inherit
