name: tailscale-ssh-centos-amd64

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH - CentOS AMD64
    uses: ./.github/workflows/reusable-tailscale-ssh.yml
    with:
      container_name: "centos"
      base_version: "latest"
      arch: "amd64"
    secrets: inherit
