name: tailscale-ssh-debian-amd64-blacksmith

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH - Debian AMD64
    uses: ./.github/workflows/reusable-tailscale-ssh-devenv.yml
    with:
      prefix_name: "dotdebian"
      runs-on: "blacksmith-2vcpu-ubuntu-2404"
      arch: "amd64"
    secrets: inherit
