name: tailscale-ssh-fedora-arm64

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH - Fedora ARM64
    uses: ./.github/workflows/reusable-tailscale-ssh.yml
    with:
      container_name: "fedora"
      base_version: "latest"
      arch: "arm64"
    secrets: inherit
