name: tailscale-ssh-dotscreen-arm64-warpbuild
run-name: Tailscale SSH for dotscreen command

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH dotscreen - WarpBuild
    uses: ./.github/workflows/reusable-tailscale-ssh-dotscreen.yml
    with:
      runs-on: "warp-ubuntu-latest-arm64-2x"
      hostname: "dotscreen"
    secrets: inherit
