name: tailscale-ssh-alpine-amd64-blacksmith

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH - Alpine AMD64
    uses: ./.github/workflows/reusable-tailscale-ssh-devenv.yml
    with:
      prefix_name: "dotalpine"
      runs-on: "blacksmith-2vcpu-ubuntu-2404"
      arch: "amd64"
    secrets: inherit
