name: tailscale-ssh-machine-amd64
run-name: Tailscale SSH with machinefile action

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH Machine - Ubuntu
    uses: ./.github/workflows/reusable-tailscale-ssh-machine.yml
    with:
      runs-on: "ubuntu-latest"
      hostname: "dotfiles-machine"
    secrets: inherit
