name: tailscale-ssh-dotscreen-arm64
run-name: Tailscale SSH for dotscreen command on Arm
on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH dotscreen - Ubuntu (ARM)
    uses: ./.github/workflows/reusable-tailscale-ssh-dotscreen.yml
    with:
      runs-on: "ubuntu-24.04-arm"
      hostname: "dotscreen-arm"
    secrets: inherit
