name: tailscale-ssh-ubi9-arm64

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH - UBI9 ARM64
    uses: ./.github/workflows/reusable-tailscale-ssh-devenv.yml
    with:
      prefix_name: "dotubi9"
      runs-on: "ubuntu-24.04"
      arch: "arm64"
      sudo-change-shell: false
    secrets: inherit
