name: tailscale-ssh-machine-arm64
run-name: Tailscale SSH with machinefile action on Arm

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH Machine - Ubuntu (ARM)
    uses: ./.github/workflows/reusable-tailscale-ssh-machine.yml
    with:
      runs-on: "ubuntu-24.04-arm"
    secrets: inherit
