name: tailscale-ssh-dotscreen-blacksmith
run-name: Tailscale SSH for dotscreen command

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH dotscreen - Blacksmith
    uses: ./.github/workflows/reusable-tailscale-ssh-dotscreen.yml
    with:
      runs-on: "blacksmith-2vcpu-ubuntu-2404"
      hostname: "dotscreen"
    secrets: inherit
