name: tailscale-ssh-almalinux-arm64

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH - AlmaLinux ARM64
    uses: ./.github/workflows/reusable-tailscale-ssh.yml
    with:
      container_name: "almalinux"
      base_version: "latest"
      runs-on: "ubuntu-24.04"
      arch: "arm64"
