name: tailscale-ssh-alpine-arm64

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH - Alpine ARM64
    uses: ./.github/workflows/reusable-tailscale-ssh-container.yml
    with:
      container_name: "alpine"
      base_version: "latest"
      runs-on: "ubuntu-24.04"
      arch: "arm64"
      sudo-change-shell: false
    secrets: inherit
