name: tailscale-ssh-debian-arm64-blacksmith

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH - Debian ARM64
    uses: ./.github/workflows/reusable-tailscale-ssh-devenv.yml
    with:
      prefix_name: "dotdebian"
      runs-on: "blacksmith-2vcpu-ubuntu-2404"
      arch: "arm64"
      sudo-change-shell: true
    secrets: inherit
