name: tailscale-ssh
run-name: Tailscale SSH with install action

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Remove unwanted stuff
        uses: gbraad-devenv/remove-unwanted@v1

      - name: Tailscale
        uses: gbraad-actions/tailscale-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          args: --ssh --accept-dns=false --operator=runner
          hostname: dotfiles

      - name: Dotfiles
        uses: gbraad-dotfiles/install-dotfiles-action@v1

      - name: Install required virtualization software
        continue-on-error: true
        run: |
          sudo apt-get update
          sudo apt install -y \
            qemu-kvm libvirt-daemon libvirt-daemon-system virtiofsd virt-manager
          sudo usermod -a -G libvirt $USER

      - name: Hang around
        run: |
          IP=`tailscale ip -4`
          echo "Use the following command to connect \`tailscale ssh runner@${IP}\`"
          sleep infinity
