name: tailscale-ssh-runner-amd64
run-name: Tailscale SSH with install action

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH Machine - Ubuntu
    uses: ./.github/workflows/reusable-tailscale-ssh-runner.yml
    with:
      runs-on: "ubuntu-latest"
    secrets: inherit
