name: tailscale-ssh-almalinux-arm64

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH - AlmaLinux ARM64
    uses: ./.github/workflows/reusable-tailscale-ssh-devenv.yml
    with:
      prefix_name: "dotalmalinux"
      runs-on: "ubuntu-24.04"
      arch: "arm64"
      sudo-change-shell: false
    secrets: inherit