name: tailscale-ssh-debian-arm64

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    name: Tailscale SSH - Debian ARM64
    uses: ./.github/workflows/reusable-tailscale-ssh.yml
    with:
      container_name: "debian"
      base_version: "latest"
      runs-on: "blacksmith-2vcpu-ubuntu-2404"
      arch: "arm64"
    secrets: inherit
